<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Plant;

class plantSeeder extends Seeder
{

  // understand?
  //yess little bit every thing is going very smoothly.
  // yes
  // let me guide u.

  // step 1 : create seeder using : php artisan make:seeder {yourSeederName}
  // step 2 : add data according to your requirement in your seeder.
  // step 3 : run the seeder : php artisan db:seeder --class={yourSeederName}
  // seeder create in database/seeders/{yourSeederName}

  // seeders help us to quicky manage and run the follow of your project without creating
  // dashboards.
  // ?ok? yess..

  // now next step make your plant migartion in single migartion.
    
    public function run()
    {
    

        $plants = array(
            array('id' => '15','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:00:21','updated_at' => '2022-07-22 22:00:21'),
            array('id' => '16','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:01:00','updated_at' => '2022-07-22 22:01:00'),
            array('id' => '17','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:01:11','updated_at' => '2022-07-22 22:01:11'),
            array('id' => '18','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:01:27','updated_at' => '2022-07-22 22:01:27'),
            array('id' => '19','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:01:41','updated_at' => '2022-07-22 22:01:41'),
            array('id' => '20','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:01:53','updated_at' => '2022-07-22 22:01:53'),
            array('id' => '21','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:02:22','updated_at' => '2022-07-22 22:02:22'),
            array('id' => '35','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:31:18','updated_at' => '2022-07-22 22:31:18'),
            array('id' => '36','common_name' => 'American Marigold','botanical_name' => 'American Marigold','plant_description' => 'nice one','temperature' => '24','max_temperature' => '','humidity' => '5','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '7','phosphorus' => '4','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => 'xamp/pic','max_light' => '','created_at' => '2022-07-22 22:49:00','updated_at' => '2022-07-22 22:49:00'),
            array('id' => '41','common_name' => 'Jasmine','botanical_name' => 'Money Plant','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '2','max_soil_ph' => '','max_humidity' => '','soil_ph' => '2','nitrogen' => '2','phosphorus' => '2','potassium' => '2','plant_type' => '2','min_light' => '','plant_image' => 'dfhharutruar','max_light' => '','created_at' => '2022-07-23 00:49:59','updated_at' => '2022-07-23 00:49:59'),
            array('id' => '44','common_name' => 'China Pink','botanical_name' => 'China Pink','plant_description' => 'China Pink	are the mostly','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php38F.tmp','max_light' => '','created_at' => '2022-07-23 16:06:55','updated_at' => '2022-07-23 16:06:55'),
            array('id' => '45','common_name' => 'Common Zinnia','botanical_name' => 'Common Zinnia','plant_description' => 'Common Zinnia are the growing plant','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php9092.tmp','max_light' => '','created_at' => '2022-07-23 18:59:00','updated_at' => '2022-07-23 18:59:00'),
            array('id' => '46','common_name' => 'Green Plant','botanical_name' => 'Green Plant','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-23 19:03:37','updated_at' => '2022-07-23 19:03:37'),
            array('id' => '49','common_name' => 'Coleus','botanical_name' => 'Coleus','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-23 20:18:50','updated_at' => '2022-07-23 20:18:50'),
            array('id' => '50','common_name' => 'Coral Bells','botanical_name' => 'Coral Bells','plant_description' => 'Common Zinnia are the growing plant','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php9212.tmp','max_light' => '','created_at' => '2022-07-23 20:19:50','updated_at' => '2022-07-23 20:19:50'),
            array('id' => '52','common_name' => 'Coral','botanical_name' => 'Coral','plant_description' => 'Common Zinnia are the growing plant','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php8C5D.tmp','max_light' => '','created_at' => '2022-07-23 20:21:59','updated_at' => '2022-07-23 20:21:59'),
            array('id' => '53','common_name' => 'Bacopa','botanical_name' => 'Sutera cordata','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-23 20:24:17','updated_at' => '2022-07-23 20:24:17'),
            array('id' => '54','common_name' => 'Peace Lilly','botanical_name' => 'Peace Lilly','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-24 22:35:43','updated_at' => '2022-07-24 22:35:43'),
            array('id' => '55','common_name' => 'Peace Lilly','botanical_name' => 'Peace Lilly','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-24 22:36:27','updated_at' => '2022-07-24 22:36:27'),
            array('id' => '56','common_name' => 'Peace Lilly','botanical_name' => 'Peace Lilly','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-24 22:38:02','updated_at' => '2022-07-24 22:38:02'),
            array('id' => '57','common_name' => 'Peace Lilly','botanical_name' => 'Peace Lilly','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-24 22:38:42','updated_at' => '2022-07-24 22:38:42'),
            array('id' => '58','common_name' => 'Peace Lilly','botanical_name' => 'Peace Lilly','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'indoor-plants-low-light-Calathea-Orbifolia-600x724.jpg','max_light' => '','created_at' => '2022-07-24 22:40:03','updated_at' => '2022-07-24 22:40:03'),
            array('id' => '59','common_name' => 'Cactus','botanical_name' => 'Cactaceae','plant_description' => 'Among the toughest of all houseplants, desert and forest cacti have a unique, stark beauty, making them a statement piece for any windowsill or brightly lit room. Some species bloom after three or four years in cultivation, and others never bloom indoors','temperature' => '35','max_temperature' => '','humidity' => 'Neutral','max_soil_ph' => '','max_humidity' => '','soil_ph' => 'Neutral','nitrogen' => '5','phosphorus' => '4','potassium' => '5','plant_type' => 'both','min_light' => '','plant_image' => 'cactus.jpg','max_light' => '','created_at' => '2022-07-25 13:58:26','updated_at' => '2022-07-25 13:58:26'),
            array('id' => '60','common_name' => 'Philodendron','botanical_name' => 'Philodendron spp.','plant_description' => 'Philodendrons make great houseplants thanks to their generally low-maintenance nature, but it\'s still important to maintain proper growing conditions to keep your plant healthy. Care for your philodendron by aiming to mimic its natural tropical environment','temperature' => '35','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => 'Philodendron.jpg','max_light' => '','created_at' => '2022-07-25 14:23:14','updated_at' => '2022-07-25 14:23:14'),
            array('id' => '61','common_name' => 'China Pink','botanical_name' => 'botanical_name','plant_description' => 'China Pink	are the mostly','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php1AB7.tmp','max_light' => '','created_at' => '2022-07-25 21:44:54','updated_at' => '2022-07-25 21:44:54'),
            array('id' => '62','common_name' => 'China Pink','botanical_name' => 'botanical_name','plant_description' => 'China Pink	are the mostly','temperature' => '34','max_temperature' => '','humidity' => '6','max_soil_ph' => '','max_humidity' => '','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '','plant_image' => 'C:\\xampp\\tmp\\php2E16.tmp','max_light' => '','created_at' => '2022-07-26 11:26:21','updated_at' => '2022-07-26 11:26:21'),
            array('id' => '64','common_name' => 'RedPlant','botanical_name' => 'Green Plant','plant_description' => 'good','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'indoor','min_light' => '','plant_image' => '1658855948.jpg','max_light' => '','created_at' => '2022-07-26 17:19:09','updated_at' => '2022-07-26 17:19:09'),
            array('id' => '65','common_name' => 'African spear plant','botanical_name' => 'Sansevieria cylindrica','plant_description' => 'African spear plants are generally very low maintenance. They will survive if you forget to water or feed them, and they can thrive being root-bound in a pot. They are hardy plants that don’t typically have problems with diseases or pests, and they’re not overly picky about their growing conditions','temperature' => '24','max_temperature' => '','humidity' => '5.5','max_soil_ph' => '','max_humidity' => '','soil_ph' => 'Neutral','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => '1658856296.jpg','max_light' => '','created_at' => '2022-07-26 17:24:56','updated_at' => '2022-07-26 17:24:56'),
            array('id' => '66','common_name' => 'Cactus','botanical_name' => 'Cactaceae','plant_description' => 'ome species bloom after three or four years in cultivation, and others never bloom indoors. Both groups of cacti are easy to care for, requiring only bright sunlight and occasional watering. Water and feeding can be cut down in the winter, when the plant goes dormant.','temperature' => '25','max_temperature' => '','humidity' => 'Neutral, acidic','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => '1659154173.jpg','max_light' => '','created_at' => '2022-07-30 04:09:34','updated_at' => '2022-07-30 04:09:34'),
            array('id' => '67','common_name' => 'Cactus','botanical_name' => 'Cactaceae','plant_description' => 'ome species bloom after three or four years in cultivation, and others never bloom indoors. Both groups of cacti are easy to care for, requiring only bright sunlight and occasional watering. Water and feeding can be cut down in the winter, when the plant goes dormant.','temperature' => '25','max_temperature' => '','humidity' => 'Neutral, acidic','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => '1659154354.jpg','max_light' => '','created_at' => '2022-07-30 04:12:34','updated_at' => '2022-07-30 04:12:34'),
            array('id' => '68','common_name' => 'Cattleya orchid','botanical_name' => 'Cattleya','plant_description' => 'The key to growing them successfully is providing the right amount of light, maintaining the proper temperature and humidity, and watering and feeding adequately.','temperature' => '25','max_temperature' => '','humidity' => '24','max_soil_ph' => '','max_humidity' => '','soil_ph' => 'Acidic','nitrogen' => '4','phosphorus' => '2','potassium' => '4','plant_type' => 'both','min_light' => '','plant_image' => '1659154630.jpg','max_light' => '','created_at' => '2022-07-30 04:17:11','updated_at' => '2022-07-30 04:17:11'),
            array('id' => '69','common_name' => 'Snake plant','botanical_name' => 'Dracaena trifasciata','plant_description' => 'Snake plant is an ideal choice for beginner gardeners because it is difficult to kill. It\'s great in a container and grows well on the floor or on tabletop displays.','temperature' => '25','max_temperature' => '','humidity' => 'Neutral','max_soil_ph' => '','max_humidity' => '','soil_ph' => '6','nitrogen' => '5','phosphorus' => '2','potassium' => '5','plant_type' => 'both','min_light' => '','plant_image' => '1659155056.jpg','max_light' => '','created_at' => '2022-07-30 04:24:17','updated_at' => '2022-07-30 04:24:17'),
            array('id' => '70','common_name' => 'common name','botanical_name' => 'botanical_name','plant_description' => 'China Pink	are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '6','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpCBBC.tmp','max_light' => '6','created_at' => '2022-08-05 19:19:27','updated_at' => '2022-08-05 19:19:27'),
            array('id' => '72','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php18DE.tmp','max_light' => '3','created_at' => '2022-08-05 20:24:14','updated_at' => '2022-08-05 20:24:14'),
            array('id' => '73','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpC8EC.tmp','max_light' => '3','created_at' => '2022-08-05 20:52:17','updated_at' => '2022-08-05 20:52:17'),
            array('id' => '74','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpC715.tmp','max_light' => '3','created_at' => '2022-08-06 04:47:27','updated_at' => '2022-08-06 04:47:27'),
            array('id' => '75','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpE8A3.tmp','max_light' => '3','created_at' => '2022-08-06 04:48:41','updated_at' => '2022-08-06 04:48:41'),
            array('id' => '76','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php9CDD.tmp','max_light' => '3','created_at' => '2022-08-06 07:07:05','updated_at' => '2022-08-06 07:07:05'),
            array('id' => '77','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpBA7.tmp','max_light' => '3','created_at' => '2022-08-07 19:34:17','updated_at' => '2022-08-07 19:34:17'),
            array('id' => '78','common_name' => 'aqsaaaa','botanical_name' => 'botanical_name','plant_description' => 'China Pink 
          are the mostly','temperature' => '6','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'outdoor','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php63C1.tmp','max_light' => '3','created_at' => '2022-08-07 19:36:50','updated_at' => '2022-08-07 19:36:50'),
            array('id' => '80','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '5','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoor','min_light' => '6','plant_image' => 'posts/rOGD6bQWKTgMcyrTVTVXBdwz1rZPfxGwtcyOTigu.jpg','max_light' => '3','created_at' => '2022-08-08 20:52:47','updated_at' => '2022-08-09 03:56:19'),
            array('id' => '81','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => 'posts/ymu0nnkDHbcqHIJNPmzSu1LWtKnB5hG5NGJZIi5Z.jpg','max_light' => '3','created_at' => '2022-08-09 04:22:04','updated_at' => '2022-08-09 04:32:37'),
            array('id' => '83','common_name' => 'Aloevera','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php42F8.tmp','max_light' => '3','created_at' => '2022-08-09 09:46:12','updated_at' => '2022-08-09 09:46:12'),
            array('id' => '84','common_name' => 'Aloevera','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpA400.tmp','max_light' => '3','created_at' => '2022-08-09 11:39:02','updated_at' => '2022-08-09 11:39:02'),
            array('id' => '85','common_name' => 'Test','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpFAEF.tmp','max_light' => '3','created_at' => '2022-08-09 15:57:10','updated_at' => '2022-08-09 15:57:10'),
            array('id' => '86','common_name' => 'Test','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpC241.tmp','max_light' => '3','created_at' => '2022-08-09 20:54:02','updated_at' => '2022-08-09 20:54:02'),
            array('id' => '87','common_name' => 'Test','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpF756.tmp','max_light' => '3','created_at' => '2022-08-09 21:10:38','updated_at' => '2022-08-09 21:10:38'),
            array('id' => '88','common_name' => 'Test','botanical_name' => 'Aloevera','plant_description' => 'Aloe vera for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpC3E9.tmp','max_light' => '3','created_at' => '2022-08-09 21:12:36','updated_at' => '2022-08-09 21:12:36'),
            array('id' => '89','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php6352.tmp','max_light' => '3','created_at' => '2022-08-10 12:57:00','updated_at' => '2022-08-10 12:57:00'),
            array('id' => '90','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpE64C.tmp','max_light' => '3','created_at' => '2022-08-10 13:01:56','updated_at' => '2022-08-10 13:01:56'),
            array('id' => '91','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpAA21.tmp','max_light' => '3','created_at' => '2022-08-10 13:04:57','updated_at' => '2022-08-10 13:04:57'),
            array('id' => '92','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => 'posts/pMgG8rJ04R9nUtpU5P3qtxQaR4JPk8TbK3vx6lIR.jpg','max_light' => '3','created_at' => '2022-08-10 13:10:21','updated_at' => '2022-08-10 13:13:05'),
            array('id' => '93','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php35BC.tmp','max_light' => '3','created_at' => '2022-08-10 13:30:40','updated_at' => '2022-08-10 13:30:40'),
            array('id' => '94','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php7448.tmp','max_light' => '3','created_at' => '2022-08-10 13:32:01','updated_at' => '2022-08-10 13:32:01'),
            array('id' => '95','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => 'posts/bUORLg9YEqaqwb3f9s1RdT1EEnIs1NA54NbVT34A.jpg','max_light' => '3','created_at' => '2022-08-10 13:38:01','updated_at' => '2022-08-10 13:41:15'),
            array('id' => '96','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => 'posts/pUlEyaobXnIwsFoVXZ4NzeXL7hdpPVfnnbLjmW7e.jpg','max_light' => '3','created_at' => '2022-08-10 13:41:49','updated_at' => '2022-08-10 13:43:24'),
            array('id' => '97','common_name' => 'Alovera','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '35','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => 'posts/MJ929dvKRzkPz4ilVpSaQuSi8WbGjQWLhXANO448.jpg','max_light' => '3','created_at' => '2022-08-10 13:47:07','updated_at' => '2022-08-10 17:28:44'),
            array('id' => '98','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php8494.tmp','max_light' => '3','created_at' => '2022-08-15 18:08:14','updated_at' => '2022-08-15 18:08:14'),
            array('id' => '99','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpD3F6.tmp','max_light' => '3','created_at' => '2022-08-20 18:43:32','updated_at' => '2022-08-20 18:43:32'),
            array('id' => '100','common_name' => 'Alovera2','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '30','max_temperature' => '4','humidity' => '10','max_soil_ph' => '5','max_humidity' => '6','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '4','plant_image' => 'new_image1661331815.jpg','max_light' => '4','created_at' => '2022-08-24 06:39:19','updated_at' => '2022-08-24 09:03:36'),
            array('id' => '101','common_name' => 'Alovera2','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '30','max_temperature' => '34','humidity' => '10','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '6','plant_image' => '','max_light' => '3','created_at' => '2022-08-24 06:44:39','updated_at' => '2022-08-24 07:02:47'),
            array('id' => '102','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php8D8B.tmp','max_light' => '3','created_at' => '2022-08-24 09:06:47','updated_at' => '2022-08-24 09:06:47'),
            array('id' => '103','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php90AF.tmp','max_light' => '3','created_at' => '2022-08-24 09:08:59','updated_at' => '2022-08-24 09:08:59'),
            array('id' => '104','common_name' => 'Alovera2','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '30','max_temperature' => '4','humidity' => '10','max_soil_ph' => '5','max_humidity' => '6','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '4','plant_image' => 'new_image1661333090.jpg','max_light' => '4','created_at' => '2022-08-24 09:09:35','updated_at' => '2022-08-24 09:24:50'),
            array('id' => '105','common_name' => 'Alovera2','botanical_name' => 'Alovera','plant_description' => 'Alovera is mostly used for skin care','temperature' => '30','max_temperature' => '4','humidity' => '10','max_soil_ph' => '5','max_humidity' => '6','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '7','plant_type' => 'indoorrr','min_light' => '4','plant_image' => 'new_image1661333250.jpg','max_light' => '4','created_at' => '2022-08-24 09:25:07','updated_at' => '2022-08-24 09:27:30'),
            array('id' => '106','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpFC80.tmp','max_light' => '3','created_at' => '2022-08-24 14:33:51','updated_at' => '2022-08-24 14:33:51'),
            array('id' => '107','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php8C00.tmp','max_light' => '3','created_at' => '2022-08-24 14:34:27','updated_at' => '2022-08-24 14:34:27'),
            array('id' => '108','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php9D08.tmp','max_light' => '3','created_at' => '2022-08-24 14:34:32','updated_at' => '2022-08-24 14:34:32'),
            array('id' => '109','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpD95A.tmp','max_light' => '3','created_at' => '2022-08-25 02:22:35','updated_at' => '2022-08-25 02:22:35'),
            array('id' => '110','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\phpFFB3.tmp','max_light' => '3','created_at' => '2022-08-25 13:26:51','updated_at' => '2022-08-25 13:26:51'),
            array('id' => '111','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'C:\\xampp\\tmp\\php813F.tmp','max_light' => '3','created_at' => '2022-08-25 14:15:27','updated_at' => '2022-08-25 14:15:27'),
            array('id' => '112','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'AfricanDaisy.jpg','max_light' => '3','created_at' => '2022-08-25 14:47:24','updated_at' => '2022-08-25 14:47:24'),
            array('id' => '113','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'alovera.jpg','max_light' => '3','created_at' => '2022-08-25 14:50:08','updated_at' => '2022-08-25 14:50:08'),
            array('id' => '114','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'Cattleya orchid.jpg','max_light' => '3','created_at' => '2022-08-25 15:00:55','updated_at' => '2022-08-25 15:00:55'),
            array('id' => '115','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'cactus.jpg','max_light' => '3','created_at' => '2022-08-27 06:26:16','updated_at' => '2022-08-27 06:26:16'),
            array('id' => '116','common_name' => 'Cattleya Orchid','botanical_name' => 'Cattleya Orchid','plant_description' => 'Cattleya Orchid for face and skin has so many benefits that it is a MUST for your skincare routine. I\'ll admit that before I started researching natural skin care, the only thing I used aloe vera for was treating sunburns. But once I realized how many uses this amazing plant has, I find myself using it more and more.
          If you\'re looking to mix up your skin care routine, it\'s time to consider aloe vera','temperature' => '35','max_temperature' => '34','humidity' => '7','max_soil_ph' => '5','max_humidity' => '34','soil_ph' => '5','nitrogen' => '6','phosphorus' => '4','potassium' => '2','plant_type' => 'both','min_light' => '6','plant_image' => 'cactus.jpg','max_light' => '3','created_at' => '2022-08-27 07:40:39','updated_at' => '2022-08-27 07:40:39')
          );


          foreach($plants as $item) {
            Plant::create($item);
          }
    }
}
